# _name = "bzd-flux"

[http]
endpoint = "0.0.0.0:3000"

[db]
endpoint = "postgres://postgres:postgres@0.0.0.0:5432/bzd_flux"

[nats]
endpoint = "0.0.0.0:4222"
stream = "bzd"

[feeds.limits]
user = 25

[feeds.messaging.messages_topics]
subjects = ["bzd.messages.events.messages_topics"]
consumer = "bzd-flux-feeds-messages-topics"


[feeds.messaging.topics_users]
subjects = ["bzd.messages.events.topics_users"]
consumer = "bzd-flux-feeds-topics-users"

[feeds.processing]
batch_size = 5
